POST http://localhost:3000/api/encode
Content-Type: application/json

{
"longUrl":"https://example.com/my/long/article?serach=k"
}

###
POST http://localhost:3000/api/decode
Content-Type: application/json

{
"shortUrl":"https://example.com/NDg"
}

###
GET  http://localhost:3000/api/list


###
GET  http://localhost:3000/api/list?search=bamboohr

###
GET  http://localhost:3000/api/NDg

###
GET  http://localhost:3000/api/statistic/NDg